travis:
  secure:
    BINSTAR_TOKEN: D066QNJmVNJGS9osqWFdh2f958gS1M6Vl3sSSc36CkGX2OTGLa9I8vOXhMmAbW3rz55IFvzgtOwpFazebKskMv1ezrazt8Ohcosck589y6fmCDELJ/dVm3f5L8MyLXKKn5g8NA+5X5sD+VscdzYEDNZ59w70lUvXD1B3CPZ2X2qckrJSqlk5XGE8cpFFWUYDYRZs/Bj9DDI6fq+kI6MZpjiztx1ZQxFHDQfW8gbAzVakROe6j4x0plxBP1EjtFD/PEZN8l/oJQ7Y+SiZ/KGzXQCbF1uI1yzZqgI5AonOjAciOsBDKCVx6HxSnqy6szLKT+qgIY+774fVQmPokfHRlUrDX2ZxT4v7oAP1ggXFuQPKc2sJSV7dvBVss/MGLnZtvsIjrMJuDPqBtklmqTZJXRZK8DgaGrjenOGnkis4A8Evp0R3T2CZ2Mxj/kyuXylGJZIifOqpthxkt5YSr+VekX0A3N7rsobGCZlwCKe9KHsUP1OnSEEY9YbU/k9MEak6gK4AWH8r3alnlh9moybaFM0rW1K7oH7KqOaXiEUhtJnq3jO8QFlpvDbfHEfayrP96c7qtM3XT+MtkgAvVSHJ2Sz3TF3+WQGWODewbtYxHti0ODnQwhSPBJNNnFS/lv5TC3IA2TFlX/bw3EMj+GNFU7NE9nCMFRK6ouJ0kDN4e6w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
