travis:
  secure:
    BINSTAR_TOKEN: IAyg5PnXhtooi3a55Wtaxk2RwrAoleUv2+TazemuwVt2SGWaw+xRg2kOT4FVEDpvTEc5TM0H3QMVt1F5fLnuWh8S1+eSG5HumEth91l+YeXsRhukML535eclklgES65DZC9N3c0wsSeAsLvUdjw45N2LCmj2UfKHFFqQGl5h7HkzohrwlkKue2c/3a0+L41rdmTQyu3/tOllBw35XxxJQtj+qbTmGQP33cOePJjKjOKdxjfkpmxjUkAfq74X4OdMtrnBQjop3ftIRv66dWGJdBUJV9GfOma3MgYobaLaYu6w3PUl0TFtycHOIztUOBk6hDToTr0Ko2hgsIeymkcaEboJixln2C0X+rLBgyO8Fdi1J6XLHceUElzdxULxdcxUAt8a0hg+jr0lLIonqHYJLQlHrYFnU39REw8Ueg/nORTQCvUzbdKQF/HHg2kfMUCyvllubnj9LCW3RWpVFDDRGesGW3Ea1YjF1NKIGEQgrPiNKppwRUJfRohbpbeDMYVfw3/rhxvAopvFILLiepoyF6Ol7t3vVl4jA9mTtgn9hxqAVAQd7k/J/2BgnYH3YkPWXnbW1zyGpYFTlj/eSjLyDcsMoTHZd3Cj6hITJio34T/c+YPqTFeG2rb/L3xm9doc85wOo55EvfsKDPo59ddN2h4go0nJSigBFF5AQQBfizo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
